### ISSUE TITLE
Firefox for Android compatibility

### ISSUE THREAD

**Issue by raxod502** [FreshSupaSulley/Duochrome#12]
Apparently, extra steps are required to make a browser extension work on Firefox for Android, as opposed to just desktop Firefox. It's not clearly documented (see https://support.mozilla.org/en-US/questions/1450700 for my complaint), but I think one step is you have to manually mark it as compatible when uploading to the addon store.

However, I also went through the steps in https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/ to test the development version of Duochrome on Firefox for Android and it looks like there may be an API compatibility issue (one or more), too: I see in the browser console the error `TypeError: json is undefined` from this function:

https://github.com/FreshSupaSulley/Duochrome/blob/dd74bc4228fb28ab9a7c7a0bfb42f3bae1719258/firefox/popup.js#L677-L683

I guess the `browser.storage.sync` API behaves differently on mobile for some reason, or the required manifest permissions to make it work are different.

I'm happy to try and implement this, if it would be an acceptable addition, since I'd rather like to be able to log in to my Duo-protected accounts without needing my laptop.

**Comment by FreshSupaSulley** [comment]
Never used Firefox on Android. I know I've had weird issues porting "experimental JS" to Firefox when it worked fine with Chrome. However, I will say `TypeError: json is undefined` really just looks like deviceInfo doesn't exist on the device yet. Could be wrong, but if not it might be a permission thing or something weird with your ecosystem you're testing it on.

Before I try supporting this for Firefox on Android (which seems like a LOT of [work](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/) I don't wanna do), can I ask you this: why not just use the Duo app if you're already on your phone? Is there an advantage to using the extension over the app? Seems like unnecessary work but I don't wanna discourage you

**Comment by raxod502** [comment]
> `TypeError: json is undefined` really just looks like deviceInfo doesn't exist on the device yet

No, if `deviceInfo` doesn't exist, the storage API should return `{deviceInfo: undefined}` rather than `undefined` entirely. Figured it out though, the storage API is broken for permissions related reasons if you don't define a `browser_specific_settings` section and provide an extension ID (this only applies to running as a temporary extension, not to published addons from the store):

```json
  "browser_specific_settings": {
    "gecko": {
      "id": "duochrome@intuitiveexplanations.com"
    }
  }
```

Turns out I discovered this 7 months ago and documented it here: https://github.com/FreshSupaSulley/Duochrome/issues/5.

Now with that workaround applied, I verified that the extension works 100% fine on mobile. So, I think the only thing you need to do to make it compatible is to enable the checkbox for "compatible with Android" when uploading to the Firefox store.

> why not just use the Duo app if you're already on your phone? Is there an advantage to using the extension over the app? 

Absolutely, the extension is open source and I have no reason or desire to trust an adversarial third party to run proprietary code on my device when there is no technical reason why it should be necessary. I have the right to own the authentication keys for my own accounts. Besides, the Duo Mobile app has gaping functionality holes, like the inability to backup keys in any way other than Google Drive (which doesn't work for me as I don't use a Google account). I've complained to them about that but they've made it clear there aren't any plans to change it.

**Comment by FreshSupaSulley** [comment]
Didn't realize you were running it as an unpacked extension - my bad. Yeah that's a weird Firefox dev thing

> Now with that workaround applied, I verified that the extension works 100% fine on mobile. So, I think the only thing you need to do to make it compatible is to enable the checkbox for "compatible with Android" when uploading to the Firefox store.

I was debating asking if I should just press the "compatible with Android" button and have you test it. Anyways I updated the Firefox listing page to 1.4.0.1 which changed nothing besides enabling that button. Really glad it works without code refactoring, didn't think it did but you never know. Let me know if there's anything else I can do.

**Comment by raxod502** [comment]
Works beautifully out of the box now :heart: 

Yeah, I was just doing the unpacked extension thing because that is the only way to install an extension onto Firefox on Android if it is not explicitly marked as compatible in the store. It's very obtuse.
