### ISSUE TITLE
Addon removed from Firefox

### ISSUE THREAD

**Issue by raxod502** [FreshSupaSulley/Duochrome#5]
The link in the README (https://addons.mozilla.org/en-US/firefox/addon/duosu/) shows this:

![image](https://github.com/FreshSupaSulley/Duochrome/assets/6559064/554a9be3-baf9-4ae5-b57c-efce52b94b3d)

### Workaround

Manually edit `firefox/manifest.json` to add:

```json
  "browser_specific_settings": {
    "gecko": {
      "id": "duochrome@example.com"
    }
  }
```

because [without an explicit extension id, the persistent storage API is not supported](https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/), which results in the extension crashing with error `json is not defined` because it cannot read or write storage. Then go to `about:debugging` in Firefox and load the `manifest.json` file as a temporary extension. It works as advertised.

**Comment by raxod502** [comment]
Oh, it's just an outdated link. I guessed the correct one, I think: https://addons.mozilla.org/en-US/firefox/addon/duochrome/

**Comment by FreshSupaSulley** [comment]
Yep, had to rename it. Was the add-on force removed for firefox users?

**Comment by FreshSupaSulley** [comment]
wait I thought you were saying the firefox add-on like blew up or something

Sorry, I had to rename it from DuOSU -> Duochrome. I tried to rename everything in the README to point to Duochome but I forgot the firefox link (the old chrome one still points to the new one so I overlooked it). Sorry for the annoyance but glad you found it
