### ISSUE TITLE
Unable to check Duo logins

### ISSUE THREAD

**Issue by TURX** [FreshSupaSulley/Duochrome#8]
<img width="314" alt="image" src="https://github.com/FreshSupaSulley/Duochrome/assets/22395704/14d35378-8608-43cd-bdc5-a930910cf2b7">

An error occured: "Duo denied handling request at /push/v2/device/transactions (was the device deleted?)"
Stack: undefined

This error persists even if I reset the extension and activate it as a new device again.

**Comment by FreshSupaSulley** [comment]
I also noticed this issue. Seems like it just magically went away and I don't understand why. The error response thrown by the Duo API was pertaining to the timestamp header attached to the transactions endpoint:
`{"code": 40105, "message": "Bad request timestamp", "stat": "FAIL"}`
Oddly, when I went to take a look at the timestamp Duochrome sends to the API, everything seemed normal. It seems Duo expects the x-duo-date to be formatted to RFC 2822, which I'm very confident Duochrome handles correctly. During the outage, I captured what timestamp Duochrome was sending to the API:
`-H 'x-duo-date: Sun, 10 Mar 2024 06:34:10 -0000'`
This seems to be perfectly normal. [This timestamp also aligns with Duo's Auth API](https://duo.com/docs/authapi-v1#authentication), although this is a different API than the undocumented one Duochrome is using.

I don't know the cause of the outage, but it works now. I'm going to keep looking into this to see if I can find a better way to approve transactions that aligns more with the phone app.
